///
/// 
/// 
/// 
/// USERS AND ROLES INTRODUCE - MOVE TO USERNAME SIGN-ON AND REGISTER
/// TO DO PURCHASING MODULE COMPLETE
/// TRANSFER TO SERVICES ALL JOBORDER , INVENTORY AND PURCHASING 
/// CHECK AND ADD VALIDATIONS FOR ALL CONTROLLERS WHERE MISSING
/// COMPLETE THE UNIT TESTING MODULE
/// 
/// RELAY ERRORS TO ERROR PAGES WITH CALL-BACK
/// 
/// 
/// 
/// SIGNALr FOR THE STATISTICS IN DASHBOARD  
/// PICTURES CREATOR PAGE
/// REWORK THE SEEDER WITH PROPER REAL VALUES 
///
///



